---
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run:
          name: Install Meteor
          command: |
            set +e
            METEOR_SYMLINK_TARGET=$(readlink ~/.meteor/meteor)
            METEOR_TOOL_DIRECTORY=$(dirname "$METEOR_SYMLINK_TARGET")
            set -e
            LAUNCHER=$HOME/.meteor/$METEOR_TOOL_DIRECTORY/scripts/admin/launch-meteor
            if [ -e $LAUNCHER ]
            then
              echo "Cached Meteor bin found, restoring it"
              sudo cp "$LAUNCHER" "/usr/local/bin/meteor"
            else
              echo "No cached Meteor bin found."
            fi

            command -v meteor >/dev/null 2>&1 || curl https://install.meteor.com | sed s/--progress-bar/-sL/g | /bin/sh
      - run:
          name: Versions
          command: |
            npm --versions
            node -v
            meteor --version
            meteor npm --versions
            meteor node -v
            git version
      - run:
          name: Meteor npm install
          command: |
            meteor npm install
      - run:
          name: Build Rocket.Chat
          command: |
            if [[ $CIRCLE_TAG ]]; then meteor reset; fi
            set +e
            meteor add rocketchat:lib
            set -e
            meteor build --server-only --directory /tmp/build-test
      - run:
          name: Prepare build
          command: |
            mkdir /tmp/build/
            cd /tmp/build-test
            tar czf /tmp/build/Rocket.Chat.tar.gz bundle
            cd /tmp/build-test/bundle/programs/server
            npm install
      - persist_to_workspace:
          root: /tmp/
          paths:
            - build-test
            - build
      - store_artifacts:
          path: /tmp/build

  build_image:
    docker:
      - image: 498457837717.dkr.ecr.ap-southeast-1.amazonaws.com/circleci:5
        aws_auth:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            cd /tmp/build
            tar xzf Rocket.Chat.tar.gz
            rm Rocket.Chat.tar.gz

            echo "Build official Docker image"
            cp ~/repo/.docker/Dockerfile .
            docker build -t 498457837717.dkr.ecr.ap-southeast-1.amazonaws.com/reitscreener_rocketchat:$CIRCLE_BUILD_NUM .
            docker push 498457837717.dkr.ecr.ap-southeast-1.amazonaws.com/reitscreener_rocketchat:$CIRCLE_BUILD_NUM

workflows:
  version: 2
  build:
    jobs:
      - build
      - build_image:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
